sudo: true

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

install:
  - sudo add-apt-repository ppa:ubuntu/fpc
  - sudo apt-get update
  - sudo apt-get install fp-compiler-3.0.4


script:
  - fpc

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL