matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

addons:
  apt:
    packages:
    - fp-compiler-3.0.0

script:
  - fpc ./s4/hw1/hw1.pas
  - fpc ./s4/cw1/cw1.pas
  - fpc ./s4/hw2/hw2.pas
  - fpc ./s4/hw3/hw3.pas
  - fpc ./s4/hw4/hw4.pas
  - fpc ./s4/cw2/task1.pas
  - fpc ./s4/cw2/random.pas
  - fpc ./s4/hw4/palindrome.pas
  - fpc ./s4/cw2/p87q6.pas

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL