sudo: true

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

before_install:
  - sudo apt-get install alien
  - wget -O "fpc.rpm" "https://downloads.sourceforge.net/project/freepascal/Linux/3.0.4/fpc-3.0.4-1.x86_64.rpm?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ffreepascal%2Ffiles%2FLinux%2F3.0.4%2Ffpc-3.0.4-1.x86_64.rpm%2Fdownload&ts=1537008154"
  - sudo alien fpc.rpm
  - sudo dpkg -i fpc_3.0.4-2_amd64.deb


script:
  - fpc

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL